### ISSUE TITLE
Site logo gets squished

### ISSUE THREAD

**Issue by le-patenteux** [melroy89/duende-v3#2]
First of all, thanks for your amazing theme, it is gorgeous and well built. The reactive component of it work amazingly. Good job!

**Now, for the issue**, when using my own logo, it gets squished because it is constrained at 299x65 px

I can't find where in the templates it is defined to change that... Can you point it to me please?

Images should only be constrained in one axis to make sure they don't get distorted upon rendering, either height, or width, no both...

**Comment by melroy89** [comment]
In the admin panel, go to:

`Templates -> Duende v3 -> Header Templates - > header`

Current default code is:

```html
<div class="float_left logo"><a href="{$mybb->settings['bburl']}/index.php"><img src="{$theme['logo']}" alt="{$mybb->settings['bbname']}" width="299" height="65" /></a></div>	
```

**Comment by le-patenteux** [comment]
Wonderful! Thank you... i forgot that the templates were separated from the theme's stylesheet... 
My days of modifying MyBB themes go far back! (my own site's branding was done years ago... I am building a new one!)

Thanks a lot!

I would suggest that you remove the width constrain in the theme, the only important bit is the height to fit correctly in the header. (and if some weirdo tries to use a 65 x 3000px logo, he has some other issues of his own to sort!)
